sudo: false
language: csharp

install:
  - gem update --system
  - gem install albacore -v 0.3.6
  - nuget restore ./src/LiteGuard.sln

script: rake

notifications:
  email:
    - liteguard.ch@gmail.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fb4c45d35154322cdbd6
